### ISSUE TITLE
There are some problems with the generated model xml file

### ISSUE THREAD

**Issue by zzlonggg** [fmipp/py-fmipp#4]
When I tried to use fmpy to simulate, an error was thrown. (Error Details: unable to parse XML model description )
I try to use fmpy to verify fmu. It found two problems. (Attached with verification results)
(ModelStructure/Outputs must have exactly one entry for each variable with causality="output".ModelStructure/InitialUnknowns does not contain the expected set of variables. Expected {Pheat} but was {}.)
Although the generated models passed the official FMU compliance checker, it still has some problems in some tool applications (such as amesim). The generated model loses its output information in amesim, leaving only the input information (Attached drawings). This makes the fmu file unusable. 
![D(VK@6W$@FNZV37 W~LMJXN](https://user-images.githubusercontent.com/101376398/203274409-26a163d8-937c-423b-8681-e7dce0776293.png)
[Controller_validation.txt](https://github.com/fmipp/py-fmipp/files/10065882/Controller_validation.txt)

**Comment by ewidl** [comment]
In commit e39b80c the model structure (outputs, initial unknowns) of an exported FMU is included into the model description. I hope this makes it also compatible with Amesim and other tools. You can install this version from PyPI via:
```
pip install fmipp==2.1.0 --prefer-binary
```
