### ISSUE TITLE
Simulation result error

### ISSUE THREAD

**Issue by zzlonggg** [fmipp/py-fmipp#5]
I have an fmu file. When simulating through fmipp, it cannot get correct results. It seems that fmipp cannot correctly assign values to the input of the model.
[testfmu.zip](https://github.com/fmipp/py-fmipp/files/10264067/testfmu.zip)

**Comment by ewidl** [comment]
Could you please provide some kind of reference for testing?

- How long do you run the simulation? 
- Did you simulate the FMU in ME or CS?
- What are your inputs for testing? 
- What the expected outputs? 

For instance, a plot of the expected simulation results from running the FMU in Dymola or OpenModelica?

Also, could you please provide the code you used for simulating the FMU with fmipp?

**Comment by zzlonggg** [comment]
I found the problem, I used `FMUCoSimulationV2` by mistake.
